service: lambda-edge-2-s3

provider:
  name: aws
  stage: ${opt:stage}
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketNameKey: RootBucket
      localDir: rootapp/
      deleteRemoved: true
    - bucketNameKey: SubBucket
      localDir: subapp/
      deleteRemoved: true

resources:
  Resources:
    RootBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
    SubBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
    RootBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: RootBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - ' '
                    - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                      - ${opt:oai}
              Action:
                - 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: RootBucket
                    - '/*'
    SubBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: SubBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - ' '
                    - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                      - ${opt:oai}
              Action:
                - 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: SubBucket
                    - '/*'
  Outputs:
    RootBucket:
      Value:
        Ref: RootBucket
    SubBucket:
      Value:
        Ref: SubBucket
